[2025-08-17 14:42:54,687] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Initializing the conversion map
Traceback (most recent call last):
  File "MotionDirector_inference.py", line 258, in <module>
    latents_path = f"{latents_folder}/{random.choice(os.listdir(latents_folder))}"
FileNotFoundError: [Errno 2] No such file or directory: './outputs/myTrain/train_Hand_80f_linear/cached_latents'
==== Experiment ====
datetime: 2025-08-17 14:43:02
checkpoint_folder: ./outputs/myTrain/train_Hand_80f_linear
prompt_index: 0
prompt: 
noise_prior: 0.1
num_frames: 80
num_steps: 100
output_dir: ./outputs/inference_long/Hand/noise0.1
==== End ====

